"""
Visual reporting: per-image VAE-vs-SPNN iteration grids, logged to wandb.

Layout mirrors the paper's Figure 2 — the input, then the edit chain left to right —
but stacks the two codecs so the divergence is read vertically at a fixed iteration:

    source | iter 1 | iter 2 | ... | iter 25     <- Vanilla SD1.5 VAE
    source | iter 1 | iter 2 | ... | iter 25     <- + SPNN

Runs are split by **editing task and model**:

    group    = the paper's Type column   (text-guided / subject-guided / mask-guided)
    run name = <tag>-<model>-<codec>     (or -compare for the two-codec comparison)
    panel    = one per sample, keyed <img_id>_t<turn>

wandb sections split on the first "/" in a key, so keying panels by sample id gives one
collapsible section per ImagenHub sample inside each run, while the run list itself is
grouped by editing task and model.
"""

import os
from pathlib import Path

from PIL import Image, ImageDraw

from .data import load_png_safe

CELL = 128
PAD = 2
LABEL_W = 96
HEADER_H = 18

_FONT = None


def _font():
    """DejaVu if the repo copy is around, else PIL's bitmap default."""
    global _FONT
    if _FONT is None:
        from PIL import ImageFont
        for p in ("latent-diffusion/data/DejaVuSans.ttf",
                  "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"):
            if os.path.exists(p):
                try:
                    _FONT = ImageFont.truetype(p, 12)
                    break
                except Exception:
                    pass
        if _FONT is None:
            _FONT = ImageFont.load_default()
    return _FONT


def build_grid(rows, row_labels, col_labels, cell=CELL):
    """rows: list of lists of PIL images (or None for a gap). Returns one PIL image."""
    ncol = max(len(r) for r in rows)
    W = LABEL_W + ncol * (cell + PAD) + PAD
    H = HEADER_H + len(rows) * (cell + PAD) + PAD
    canvas = Image.new("RGB", (W, H), (255, 255, 255))
    d = ImageDraw.Draw(canvas)
    f = _font()

    for c, lab in enumerate(col_labels[:ncol]):
        x = LABEL_W + c * (cell + PAD)
        d.text((x + 2, 3), str(lab), fill=(0, 0, 0), font=f)

    for r, (imgs, lab) in enumerate(zip(rows, row_labels)):
        y = HEADER_H + r * (cell + PAD)
        d.text((4, y + cell // 2 - 6), lab, fill=(0, 0, 0), font=f)
        for c, im in enumerate(imgs):
            if im is None:
                continue
            canvas.paste(im.convert("RGB").resize((cell, cell), Image.LANCZOS),
                         (LABEL_W + c * (cell + PAD), y))
    return canvas


def mask_overlay(source, mask, colour=(255, 0, 64), alpha=0.45):
    """Tint the masked region over the source, so the edit area is legible in context.

    The bare mask shows the shape; the overlay shows *what* it selects. Both are useful
    and neither substitutes for the other.
    """
    from PIL import Image as _I
    base = source.convert("RGB")
    tint = _I.new("RGB", base.size, colour)
    m = mask.convert("L").resize(base.size, _I.NEAREST).point(
        lambda v: int(alpha * 255) if v > 127 else 0)
    return _I.composite(_I.blend(base, tint, alpha), base, m.point(lambda v: 255 if v else 0))


def build_inputs_grid(sample, model, cell=CELL):
    """The conditioning actually fed to this editor, as one labelled strip.

    Mirrors the paper's Figure 4, which shows each edit's inputs (reference image +
    mask) beneath the iteration chain. Contents vary by task:

      mask-guided     (sd_inpaint) : source, mask, overlay
      subject-guided  (pbe)        : source, mask, overlay, x_r^1, x_r^2
      text-guided     (ip2p, ...)  : source only; the conditioning is text, so it goes
                                     in the caption rather than the strip
    """
    imgs = [sample.source]
    labels = ["source"]
    if model in ("sd_inpaint", "pbe"):
        imgs += [sample.mask, mask_overlay(sample.source, sample.mask)]
        labels += ["mask m", "mask on source"]
    if model == "pbe":
        imgs += [sample.ref_target, sample.ref_source]
        labels += ["ref x_r^1 (target obj)", "ref x_r^2 (original obj)"]
    return build_grid([imgs], ["inputs"], labels, cell=cell)


def inputs_caption(sample, model):
    """The text conditioning, spelled out with the direction it alternates in."""
    if model in ("ip2p", "magicbrush"):
        return (f"odd iters: {sample.instruction!r} | "
                f"even iters: {sample.reverse_instruction!r}")
    if model == "diffedit":
        return (f"odd iters: {sample.source_caption!r} -> {sample.target_caption!r} | "
                f"even iters: reversed. Mask is generated by DiffEdit per iteration, "
                f"not supplied.")
    if model == "sd_inpaint":
        return f"every iter: {sample.target_local_caption!r} inpainted into mask m"
    if model == "pbe":
        return ("no text; alternates reference between x_r^1 (target object) and "
                "x_r^2 (original object) within the same mask m")
    return ""


def _iter_dirs(arm: Path):
    """Every iter_NN directory present, in iteration order."""
    out = []
    for p in sorted(arm.glob("iter_*")):
        try:
            out.append((int(p.name.split("_")[1]), p))
        except (IndexError, ValueError):
            continue
    return sorted(out)


def build_image_grids(out_root, tag, models, codecs, samples, max_cols=None):
    """Yield (key, PIL grid) for every (sample, model) that has any output on disk."""
    root = Path(out_root) / tag
    label = {"vae": "own VAE (baseline)", "spnn": "+ SPNN"}

    for model in models:
        arms = {c: root / model / c for c in codecs}
        iters = {c: _iter_dirs(a) for c, a in arms.items()}
        present = [c for c in codecs if iters.get(c)]
        if not present:
            continue
        # Union of iterations across arms so a partially-finished arm still renders.
        all_iters = sorted({i for c in present for i, _ in iters[c]})
        if max_cols and len(all_iters) > max_cols:
            step = max(1, len(all_iters) // max_cols)
            all_iters = all_iters[::step][:max_cols]

        for s in samples:
            rows, row_labels = [], []
            for c in present:
                by_it = dict(iters[c])
                imgs = [s.source]
                for i in all_iters:
                    p = by_it.get(i, Path("/nonexistent")) / f"{s.key}.png"
                    imgs.append(load_png_safe(p))   # None if missing or truncated
                if all(im is None for im in imgs[1:]):
                    continue
                rows.append(imgs)
                row_labels.append(label.get(c, c))
            if not rows:
                continue
            yield f"{s.key}/{model}", build_grid(
                rows, row_labels, ["source"] + [str(i) for i in all_iters])


def start_run(project, entity, tag, model, codec, extra_config=None):
    """One wandb run per (editing task, model, codec), grouped by task type."""
    import wandb
    from .editors import TASK_TYPE

    # Include the slurm job id in the name. Without it a cancelled or preempted arm
    # leaves a "crashed" run with the SAME name as its replacement, and there is no way
    # to tell the dead one from the live one in the workspace. Resubmission after
    # preemption is normal here, so name collisions would otherwise pile up.
    job = os.environ.get("SLURM_JOB_ID")
    suffix = f"-j{job}" if job else ""
    cfg = {"tag": tag, "model": model, "codec": codec,
           "task_type": TASK_TYPE.get(model, "unknown"),
           "slurm_job_id": job}
    cfg.update(extra_config or {})
    return wandb.init(
        project=project, entity=entity,
        name=f"{tag}-{model}-{codec}{suffix}",
        group=TASK_TYPE.get(model, "unknown"),
        job_type=codec,
        tags=[model, codec, TASK_TYPE.get(model, "unknown"), tag],
        config=cfg,
        # `reinit` as a bool is deprecated; "finish_previous" is the modern spelling of
        # what we want -- close any open run before starting this arm's.
        **({"reinit": "finish_previous"} if _supports_reinit_str() else {}),
    )


def _supports_reinit_str():
    """Newer wandb takes reinit as a string; older ones only accept a bool."""
    try:
        import wandb
        major, minor = (int(x) for x in wandb.__version__.split(".")[:2])
        return (major, minor) >= (0, 19)
    except Exception:
        return False


def log_sample_grid(run, key, images, row_label, col_labels):
    """Log one sample's iteration strip into the run, as its own wandb section."""
    import wandb
    grid = build_grid([images], [row_label], col_labels)
    run.log({key: wandb.Image(grid, caption=f"{key} — {row_label}")})


def log_report(out_root, tag, models, codecs, samples, project, entity=None,
               metrics=None, max_cols=None, run_name=None):
    """One comparison run per model (grouped by editing task), each holding the
    two-codec iteration grids for every sample plus that model's metric rows."""
    import wandb
    from .editors import TASK_TYPE

    total = 0
    for model in models:
        grids = list(build_image_grids(out_root, tag, [model], codecs, samples,
                                       max_cols=max_cols))
        model_metrics = (metrics or {}).get(model)
        if not grids and not model_metrics:
            continue

        run = start_run(project, entity, tag, model, "compare",
                        extra_config={"codecs": list(codecs),
                                      "n_samples": len(samples)})
        by_key = {s.key: s for s in samples}
        for key, grid in grids:
            # key is "<img_id>_t<turn>/<model>"; the run is already model-specific, so
            # re-key as "<sample>/..." — wandb sections split on the first "/", giving
            # one section per image holding both the iterations and the inputs.
            sample_key = key.split("/")[0]
            payload = {f"{sample_key}/iterations":
                       wandb.Image(grid, caption=f"{sample_key} — {model}")}
            smp = by_key.get(sample_key)
            if smp is not None:
                payload[f"{sample_key}/inputs"] = wandb.Image(
                    build_inputs_grid(smp, model),
                    caption=inputs_caption(smp, model))
            run.log(payload)
        total += len(grids)

        if model_metrics:
            cols = ["codec", "iterations", "n", "mse", "psnr", "lpips", "ssim", "fid"]
            table = wandb.Table(columns=cols)
            for codec, per_k in model_metrics.items():
                for k, m in sorted(per_k.items()):
                    table.add_data(codec, k, m.get("n"), m.get("mse"), m.get("psnr"),
                                   m.get("lpips"), m.get("ssim"), m.get("fid"))
                    for name in ("mse", "psnr", "lpips", "ssim", "fid"):
                        if m.get(name) is not None:
                            run.summary[f"{codec}/{name}@{k}"] = m[name]
            run.log({"metrics": table})
        print(f"  {model} ({TASK_TYPE.get(model)}): {len(grids)} grids"
              f"{' + metrics' if model_metrics else ''}")
        run.finish()
    return total
